/*
 * ErrorReporterHelper.java
 *
 * Created on 12. Mai 2007, 17:29
 */

package lbms.azsmrc.remote.client.swing;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

import javax.swing.JOptionPane;

import lbms.azsmrc.remote.client.internat.I18N;
import lbms.azsmrc.remote.client.swtgui.ErrorReporter;
import lbms.azsmrc.remote.client.swtgui.ErrorReporterListener;

/**
 * 
 * @author Leonard
 */
public class ErrorReporterDialog extends javax.swing.JFrame {

	private static final String PFX = "dialog.errordialog.";

	private ErrorReporter reporter;

	/** Creates new form ErrorReporterHelper */
	public ErrorReporterDialog(ErrorReporter error) {
		reporter = error;
		initComponents();
		error.addListener(new ErrorReporterListener() {
			/*
			 * (non-Javadoc)
			 * 
			 * @see lbms.azsmrc.remote.client.swtgui.ErrorReporterListener#errorSubmitted(boolean)
			 */
			public void errorSubmitted(boolean submitted) {
				JOptionPane.showMessageDialog(null, I18N.translate(PFX+"send."+submitted));
				if (submitted) {
					ErrorReporterDialog.this.dispose();
				}
			}

			/*
			 * (non-Javadoc)
			 * 
			 * @see lbms.azsmrc.remote.client.swtgui.ErrorReporterListener#redirectTo(java.lang.String)
			 */
			public void redirectTo(String url) {
				int result = JOptionPane.showConfirmDialog(null, I18N
						.translate(PFX + "redirect")+ "\n" + url, "",
						JOptionPane.OK_OPTION | JOptionPane.CANCEL_OPTION);
				if (result == JOptionPane.OK_OPTION) {
					try {
						Desktop.getDesktop().browse(new URI(url));
					} catch (IOException e) {
						e.printStackTrace();
					} catch (URISyntaxException e) {
						e.printStackTrace();
					}
				}

			}

			/*
			 * (non-Javadoc)
			 * 
			 * @see lbms.azsmrc.remote.client.swtgui.ErrorReporterListener#showText(java.lang.String)
			 */
			public void showText(String text) {
				new Helper(text);
			}
		});
		this.setTitle(I18N.translate(PFX + "shell.text"));
		errorIDText.setText(error.getErrorID());
		stackTraceText.setText(error.getStackTrace());
		systemInfoText.setText(error.getSystemInfo());
		errorRepotLabel.setText(I18N.translate(PFX + "errorlogLabel.text"));
		errorIDLabel.setText(I18N.translate(PFX + "errorIDTextLabel.text"));
		additionalInfoLabel.setText(I18N.translate(PFX + "additionalInfoLabel.text"));
		sendAddressCheckBox.setText(I18N.translate(PFX + "sendemail.text"));
		sendBtn.setText(I18N.translate(PFX + "send_button.text"));
		sendMailBtn.setText(I18N.translate(PFX + "email_button.text"));
		c2cBtn.setText(I18N.translate(PFX + "copyToClip_button.text"));
		closeBtn.setText(I18N.translate(PFX + "close_button.text"));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {

		errorRepotLabel = new javax.swing.JLabel();
		errorIDLabel = new javax.swing.JLabel();
		errorIDText = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		stackTraceText = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		systemInfoText = new javax.swing.JTextArea();
		jPanel1 = new javax.swing.JPanel();
		additionalInfoLabel = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		additionalInfoText = new javax.swing.JTextArea();
		sendAddressCheckBox = new javax.swing.JCheckBox();
		emailAddress = new javax.swing.JTextField();
		sendBtn = new javax.swing.JButton();
		sendMailBtn = new javax.swing.JButton();
		c2cBtn = new javax.swing.JButton();
		closeBtn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		errorRepotLabel.setText("Error Report");

		errorIDLabel.setText("Error ID:");

		errorIDText.setEditable(false);

		stackTraceText.setColumns(20);
		stackTraceText.setEditable(false);
		stackTraceText.setRows(5);
		jScrollPane1.setViewportView(stackTraceText);

		systemInfoText.setColumns(20);
		systemInfoText.setEditable(false);
		systemInfoText.setRows(5);
		jScrollPane2.setViewportView(systemInfoText);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		additionalInfoLabel.setText("jLabel2");

		additionalInfoText.setColumns(20);
		additionalInfoText.setRows(5);
		jScrollPane3.setViewportView(additionalInfoText);

		sendAddressCheckBox.setText("Send Email Address with report");
		sendAddressCheckBox.setBorder(javax.swing.BorderFactory
				.createEmptyBorder(0, 0, 0, 0));
		sendAddressCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
		sendAddressCheckBox
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						sendAddressCheckBoxActionPerformed(evt);
					}
				});

		emailAddress.setEditable(false);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																592,
																Short.MAX_VALUE)
														.addComponent(
																additionalInfoLabel)
														.addComponent(
																sendAddressCheckBox)
														.addComponent(
																emailAddress,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																592,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(additionalInfoLabel)
										.addGap(18, 18, 18)
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(sendAddressCheckBox)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												emailAddress,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		sendBtn.setText("Send");
		sendBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sendBtnActionPerformed(evt);
			}
		});

		sendMailBtn.setText("Send By Mail");
		sendMailBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sendMailBtnActionPerformed(evt);
			}
		});

		c2cBtn.setText("Copy to Clipboard");
		c2cBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				c2cBtnActionPerformed(evt);
			}
		});

		closeBtn.setText("Close");
		closeBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				closeBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																616,
																Short.MAX_VALUE)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																616,
																Short.MAX_VALUE)
														.addComponent(
																errorRepotLabel)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				errorIDLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				errorIDText,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				564,
																				Short.MAX_VALUE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				sendBtn)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				sendMailBtn)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				c2cBtn)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				264,
																				Short.MAX_VALUE)
																		.addComponent(
																				closeBtn)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(errorRepotLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												197,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																errorIDLabel)
														.addComponent(
																errorIDText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												189,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(sendBtn)
														.addComponent(
																sendMailBtn)
														.addComponent(c2cBtn)
														.addComponent(closeBtn))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void sendAddressCheckBoxActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sendAddressCheckBoxActionPerformed
		emailAddress.setEditable(sendAddressCheckBox.isSelected());
	}// GEN-LAST:event_sendAddressCheckBoxActionPerformed

	private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_closeBtnActionPerformed
		this.dispose();
	}// GEN-LAST:event_closeBtnActionPerformed

	private void c2cBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_c2cBtnActionPerformed
		// TODO add your handling code here:

	}// GEN-LAST:event_c2cBtnActionPerformed

	private void sendMailBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sendMailBtnActionPerformed
		storeValues();
		reporter.sendPerEMail();
	}// GEN-LAST:event_sendMailBtnActionPerformed

	private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sendBtnActionPerformed
		storeValues();
		reporter.sendToServer();
	}// GEN-LAST:event_sendBtnActionPerformed

	private void storeValues() {
		reporter.setAdditionalInfo(additionalInfoText.getText());
		reporter.setEmail(emailAddress.getText());
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel additionalInfoLabel;

	private javax.swing.JTextArea additionalInfoText;

	private javax.swing.JButton c2cBtn;

	private javax.swing.JButton closeBtn;

	private javax.swing.JTextField emailAddress;

	private javax.swing.JLabel errorIDLabel;

	private javax.swing.JTextField errorIDText;

	private javax.swing.JLabel errorRepotLabel;

	private javax.swing.JPanel jPanel1;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JScrollPane jScrollPane2;

	private javax.swing.JScrollPane jScrollPane3;

	private javax.swing.JCheckBox sendAddressCheckBox;

	private javax.swing.JButton sendBtn;

	private javax.swing.JButton sendMailBtn;

	private javax.swing.JTextArea stackTraceText;

	private javax.swing.JTextArea systemInfoText;
	// End of variables declaration//GEN-END:variables

}
